import type { ScamConfig } from '@/types/scam'

export const DEFAULT_CONFIG: ScamConfig = {
  _meta: { version: 1, updatedAt: '', note: 'bundled fallback' },

  legitimateDomains: [
    'gov.gr', 'aade.gr', 'myaade.gov.gr', 'efka.gov.gr', 'minedu.gov.gr',
    'ypes.gov.gr', 'elta.gr', 'dei.gr', 'deddie.gr', 'desfa.gr',
    'eurobank.gr', 'alpha.gr', 'nbg.gr', 'piraeusbank.gr', 'winbank.gr',
    'eurobank.com.gr', 'cosmote.gr', 'wind.gr', 'vodafone.gr', 'nova.gr',
    'taxisnet.gov.gr', 'e-efka.gov.gr',
    'eopyy.gov.gr', 'fuelpass.gov.gr', 'powerpass.gov.gr', 'epass.gov.gr',
    'yme.gov.gr', 'netflix.com', 'amazon.com', 'amazon.co.uk',
    'microsoft.com', 'apple.com', 'icloud.com',
    'fedex.com', 'dhl.com', 'ups.com',
    'skroutz.gr', 'e-shop.gr', 'public.gr',
    'stoiximan.gr',
    'cosmoteinsurance.gr', 'cosmote.go.link',
    'box.go.link', 'boxfood.page.link',
    'g.page',
  ],

  phishingDomains: [],

  manualPhishingDomains: [
    'myaade-gr.ru', 'aade-online.xyz', 'elta-tracking.top',
    'dei-payment.click', 'efka-online.site',
  ],

  suspiciousTlds: [
    '.ru', '.xyz', '.tk', '.top', '.click',
    '.online', '.site', '.shop', '.live',
    '.info', '.vip', '.icu', '.support', '.cc', '.digital', '.network',
    '.invalid',  // synthetic placeholder used in defanged examples
  ],

  greek: {
    urgencyWords: [
      'αμεσα', 'αμεσως', 'επειγον', 'τωρα', 'σημερα',
      'εντος', '24 ωρες', '48 ωρες', '12 ωρες', 'ληγει', 'λιγει',
      'απαιτειται', 'αμελλητι', 'urgent', 'immediately',
      'expire', 'expires', 'deadline',
      'εκπνοη', 'εκπνεει', 'τελευταια ευκαιρια', 'προθεσμια', 'καταληκτικη',
      'αμεση δραση', 'αμεση ενεργεια', 'αμεσα χρηματα',
      'εντος 24', 'εντος 12', 'λιγει σημερα', 'ληγει σημερα',
    ],
    fearWords: [
      'αποκλεισμος', 'απενεργοποιηση', 'αναστολη',
      'παγωμενος', 'μπλοκαρε', 'blocked', 'suspended', 'disabled',
      'κλειδωμα', 'κλειδωθηκε', 'διαγραφη', 'απαγορευση',
      'παραβιαση', 'unauthorized', 'illegal', 'παρανομη',
      'ιος', 'μολυνθηκε', 'μολυνση', 'χακαρ', 'hacked', 'επιθεση', 'κινδυνος',
      'διαρροη', 'κλεψιμο', 'κλεφτης', 'κλεφτες',
      'διακοπη', 'φραγη', 'περιορισμος', 'θα περιοριστει', 'θα ληξει',
      'ύποπτη δραστηριοτητα', 'υποπτη δραστηριοτητα', 'ύποπτη συναλλαγη',
      'απεστειλε νεα συσκευη', 'νεα συσκευη', 'αντικατασταση sim',
    ],
    credentialWords: [
      'κωδικ', 'password', 'pin', 'otp',
      'αριθμος καρτ', 'αριθμο καρτ', 'cvv', 'cvc', 'iban',
      'τραπεζικ', 'στοιχει', 'επιβεβαιωσ',
      'verification', 'verify',
      'αριθμος λογαριασμ', 'αριθμο λογαριασμ',
      'one-time', 'one time', 'αυθεντικοποιηση', '2fa', 'sms code',
      'username', 'αφμ', 'αμκα', 'αριθμο ταυτοτητας', 'αριθμος ταυτοτητας',
      'ταυτοτητα', 'διαβατηριο', 'αριθμος διαβατηριου',
      'e-banking', 'ebanking', 'web banking', 'mobile banking',
      'αριθμος καρτας', 'στοιχεια καρτας', 'στοιχεια λογαριασμου',
      'συνδεθ', 'ταυτοποιησ', 'βαλε καρτ', 'βαλτε καρτ',
    ],
    paymentWords: [
      'πληρωση', 'πληρωσε', 'πληρωστε', 'payment', 'pay',
      'χρεωση', 'οφειλη', 'ληξιπροθεσμη', 'χρεος',
      'εκκρεμοτητα', 'εκκρεμει', 'ποσο', 'ευρω', '€', 'προστιμο', 'φορος',
      'ανεξοφλητ', 'απληρωτ', 'διοδι', 'παραβαση', 'εισφορ', 'τελη',
      'αντιτιμο', 'συνδρομη', 'τελος', 'κοστος',
      'αποζημιωση', 'επιστροφη χρηματων',
      'χρεωση αποστολης', 'τελη αποστολης', 'τελη τελωνειου',
      'εξοδα αποστολης', 'τελος σταθμευσης', 'συνταξη',
    ],
    rewardWords: [
      'κερδισ', 'κερδιζ', 'κερδη', 'νικητης', 'δωρο', 'prize', 'winner',
      'congratulations', 'συγχαρητηρια', 'επιστροφη',
      'επιστροφη φορου', 'refund', 'cashback', 'bonus',
      'εκπληξη', 'δωρεαν', 'free', 'gift',
      'επιδομα', 'αποζημιωση', 'φορολοταρια', 'voucher',
      'επιδοτηση', 'χρηματοδοτηση', 'επιχορηγηση',
      'επιστροφη χρηματων', 'επιστροφη φαρμακων', 'αποζημιωση φαρμακων',
      'εγκριθηκε επιδομα', 'εγκριθηκε επιστροφη', 'λαβετε χρηματα',
      'δικαιουστε', 'δικαιουσθε',
    ],
    brands: [
      { name: 'ΑΑΔΕ / Εφορία', keywords: ['ααδε', 'aade', 'εφορια', 'taxisnet', 'myaade'], domains: ['aade.gr', 'myaade.gov.gr', 'taxisnet.gov.gr'] },
      { name: 'ΕΛΤΑ', keywords: ['ελτα', 'elta', 'ταχυδρομει', 'δεμα', 'parcel', 'τελωνει'], domains: ['elta.gr'] },
      { name: 'ΔΕΗ', keywords: ['δεη', 'dei', 'ρευμα', 'ηλεκτρικο'], domains: ['dei.gr', 'deddie.gr'] },
      { name: 'Eurobank', keywords: ['eurobank'], domains: ['eurobank.gr'] },
      { name: 'Alpha Bank', keywords: ['alpha bank', 'alphabank'], domains: ['alpha.gr'] },
      { name: 'Εθνική Τράπεζα', keywords: ['nbg', 'εθνικη τραπεζα', 'national bank'], domains: ['nbg.gr'] },
      { name: 'Τράπεζα Πειραιώς', keywords: ['πειραιως', 'piraeus', 'winbank'], domains: ['piraeusbank.gr', 'winbank.gr'] },
      { name: 'Cosmote / e-pay', keywords: ['cosmote', 'e-pay', 'epay'], domains: ['cosmote.gr', 'cosmoteinsurance.gr'] },
      { name: 'ΕΦΚΑ', keywords: ['εφκα', 'efka'], domains: ['efka.gov.gr', 'e-efka.gov.gr'] },
      { name: 'Ελληνική Αστυνομία', keywords: ['αστυνομια', 'police', 'ελληνικη αστυνομια'], domains: [] },
      { name: 'ΕΟΠΥΥ', keywords: ['εοπυυ', 'eopyy', 'ασφαλιστικη ικανοτητα', 'υγειονομικη'], domains: ['eopyy.gov.gr'] },
      { name: 'Fuel Pass / Power Pass', keywords: ['fuel pass', 'power pass', 'epass', 'καυσιμ επιδομ'], domains: ['fuelpass.gov.gr', 'powerpass.gov.gr', 'epass.gov.gr'] },
      { name: 'Netflix', keywords: ['netflix', 'συνδρομη netflix'], domains: ['netflix.com'] },
      { name: 'Amazon', keywords: ['amazon', 'prime'], domains: ['amazon.com', 'amazon.co.uk'] },
      { name: 'Microsoft / Apple', keywords: ['microsoft', 'windows', 'apple support', 'icloud'], domains: ['microsoft.com', 'apple.com', 'icloud.com'] },
      { name: 'Τροχαία / ΥΜΕ', keywords: ['τροχαια', 'yme', 'υπ. μεταφορων', 'αδεια οδηγησης', 'κτεο', 'διοδι', 'κλιση τροχαιας'], domains: ['yme.gov.gr'] },
      { name: 'Courier / Delivery', keywords: ['fedex', 'dhl', 'ups', 'boxnow', 'speedex', 'acs courier', 'γενικη ταχυδρομικη', 'courier'], domains: ['fedex.com', 'dhl.com', 'ups.com'] },
      { name: 'Δήμος / Parking', keywords: ['δημος', 'δήμος', 'σταθμευση', 'σταθμευσης', 'τελος σταθμευσης', 'parkingpay'], domains: [] },
      { name: 'ePass / Διόδια', keywords: ['epass', 'e-pass', 'διοδια', 'τελη διελευσης', 'διελευσης', 'road fee'], domains: ['epass.gov.gr'] },
    ],
  },
}
